# Generated by Django 5.1.6 on 2025-03-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_useraccount_login_otp_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='login_ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
